server:
  port: 10300

spring:
  datasource:
#    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/mastercard;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
#    initialization-mode: always
    auto-commit: true
    jpa:
      dialect: org.h2.Driver
      show-sql: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  cache:
    type: none

dirLog: /opt/shopping/log

logging:
  path: ${dirLog}/
  file: ${dirLog}/shopping-app.log
  pattern.console:
  pattern.file: "%d{yyyy-MM-dd HH:mm:ss} | [%thread] | %-5level | %logger{36}.%M - %msg%n"
  file.max-size: 1MB
  file.max-history: 7
  level:
    #    org.springframework: trace
    # org.hibernate.SQL: debug
