

logging:
  level:
    com.self.sprintboot.learning.shopping: DEBUG

spring.output.ansi.enabled: always


spring:
  application:
    name: shopping-service
  profiles:
    active: test
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
#        show_sql: false
#        use_sql_comments: false
#        format_sql: false
#    hibernate:
#      ddl-auto: none



