server:
  port: 10300

spring:
  datasource:
    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:tcp://localhost/~/mastercard;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    initialization-mode: always
    auto-commit: true
    jpa:
      dialect: org.h2.Driver
      show-sql: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  cache:
    type: none

dirLog: /opt/shopping/log

logging:
#  file.clean-history-on-start: true
#  file.cleanHistoryOnStart: true
#  file.clearHistoryOnStart: true
  path: ${dirLog}/
  file.name: ${dirLog}/shopping-app.log
  pattern.console: "%M - %msg%n"
#  pattern.file: "%d{yyyy-MM-dd HH:mm:ss} | [%thread] | %-5level | %logger{36}.%M - %msg%n"
  pattern.file: "%M - %msg%n"
#  pattern.rolling-file-name: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  logback.rollingpolicy.file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file.max-size: 1MB
  file.max-history: 5
  level:
    #    org.springframework: trace
    # org.hibernate.SQL: debug
spring.output.ansi.enabled: always