

logging:
  level:
    com.self.sprintboot.learning.shopping: DEBUG

spring.output.ansi.enabled: always



spring:
  application:
    name: shopping-service
  profiles:
    active: test

promo1discount : 0.5
promo1freeAt : 2
promo2discount : 0
promo2freeAt : 3




