spring.application.name: boot-admin-client
spring.boot.admin.client.instance.service-base-url: http://localhost:10000
spring.boot.admin.client.url: http://localhost:10000
#spring.main:
#  allow-bean-definition-overriding: true
#  lazy-initialization: true
#spring.mvc:
#  pathmatch:
#    matching-strategy: ant_path_matcher

springdoc.api-docs.path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    com.self.sprintboot.learning.shopping: DEBUG

spring.output.ansi.enabled: always
spring.h2.console.enabled: true



spring:
  application:
    name: shopping
  profiles:
    active: test

promo1discount : 0.5
promo1freeAt : 2
promo2discount : 0
promo2freeAt : 3




